version: "3.9"

x-app: &build
  build: .
  restart: always

x-env: &env
  env_file:
    - .env

services:
  back:
    <<: [*build, *env]
    container_name: forms
    expose:
      - 8000
    depends_on:
      - mongodb

  mongodb:
    <<: *env
    container_name: forms_mongo
    image: mongo:7-jammy
    restart: unless-stopped
    expose:
      - 27017
    volumes:
      - forms_mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    command:
      mongod --quiet --logpath /dev/null

volumes:
  forms_mongo:
