version: "3.9"

services:
  back:
    ports:
      - "8000:8000"
    environment:
      APP_LOGLEVEL: debug
    volumes:
      - ./:/app

  mongodb:
    ports:
      - "27017:27017"
    volumes:
      - ./data:/mongo_dump